### ISSUE TITLE
Assembly

### ISSUE THREAD

**Issue by davetang** [DaehwanKimLab/hisat-genotype#13]
Hello,

I'm interested in the assembled allele but if I run the following:

```
hisatgenotype --assembly --assembly-verbose --threads 4 --base hla --locus-list A -1 ILMN/NA12892.extracted.1.fq.gz -2 ILMN/NA12892.extracted.2.fq.gz
```

There is no assembled allele and no reported allele in `assembly_graph-hla-NA12892_extracted_1_fq_gz-hla-extracted-1_fq.report`.

Thanks again,
Dave

**Comment by chbe-helix** [comment]
Hi Dave,

There should be a pdf output with a graphical output of the assembly. Would you prefer a FASTA file output of the assembly/contigs?

Thanks,
Chris

**Comment by davetang** [comment]
Hi Chris,

I couldn't find any PDF output and FASTA output would be perfect! For the PDF output, is `pandoc` or some other external tool required?

Also, does specifying assembly output suppress the normal reporting? When I used `--assembly`, the report file was generated but it didn't contain the genotypes.

Thanks,
Dave

**Comment by chbe-helix** [comment]
Hi Dave,

No there shouldn't be anything else required. It sounds to me like something is stalling and it isn't running. Let me run some tests on my workstation in the coming weeks to see what the problem is. I'm currently working on another publication so forgive me for the delay. 

I'm adding FASTA output for assembly to my list to add to v1.3.1 of HISATgenotype. If you're interested, I can see about getting the development branch of HISATgenotype updated and give you an update for when the errors you have reported are corrected in that branch.

Thanks,
Chris

**Comment by davetang** [comment]
Hi Chris,

thank you so much for all your help! I would be very interested in testing a developmental version so please keep me posted.

Good luck with your manuscript!

Cheers,
Dave

**Comment by chbe-helix** [comment]
Hi Dave,

The new version of HISATgenotype (1.3.1) has been released and has fixes for these issues. Please upgrade to the new version to apply these bug fixes. I have also added a fasta output for the assemblies. Thanks!

Thanks,
Chris
